### ISSUE TITLE
Integrating with PCL

### ISSUE THREAD

**Issue by soulslicer** [bmerry/mlsgpu#8]
Good day,

I see that your project is the only open source implementation of MLS on the GPU. I'd like to be able to use it in my project and of course reference your paper accordingly. 

However, I'm looking through your code and having difficulty finding a test code, where MLS is applied on a point cloud dataset and the output can be seen. Is there such a test file? I assume there is no PCL support yes? I would have to write a bridge between your point cloud format and PCL?

Thanks

**Comment by bmerry** [comment]
Hi

mlsgpu is a program rather than a library. The main program mlsgpu.cpp will take point cloud input and produce an output file. See http://bmerry.github.io/mlsgpu/ for documentation on how to run it and the input and output formats it supports.

There is no use of/connection to PCL. If you wanted to integrate with PCL features, you'd need to either convert the input point cloud to PLY and run the program, or you'd need to modify the code.

By the way, I haven't touched any of this for several years, and I barely remember how any of it works. I wouldn't be able to give you help with code changes.

**Comment by soulslicer** [comment]
Hi Bruce, I am yet to read through your paper. Can I know if this works on unorganized point clouds?

**Comment by bmerry** [comment]
It's been a long time since I looked at this, so the paper will probably answer your questions better than I will. From what I remember, it will function on totally unorganised point clouds, but the performance will suck badly if there isn't some degree of spatial coherence. It's designed for laser range-scanned data, where the raster pattern of the scanner provides organisation.
